Use unix versions on Illumos
Illumos is the OpenSolaris-based OS core of OpenIndiana, SmartOS, etc.

Did not enable the dbus path because:

  go: downloading github.com/godbus/dbus/v5 v5.1.0
  # github.com/godbus/dbus/v5
  ../../go/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/conn.go:147:17: undefined: getSystemBusPlatformAddress
  ../../go/pkg/mod/github.com/godbus/dbus/v5@v5.1.0/conn.go:174:14: undefined: getSystemBusPlatformAddress